### PR TITLE
3.2 - 19/09/2019 - bunch of new tools and update (xcmss 3.0)

### PR DESCRIPTION
**Pull request by lecorguille**
- UPGRADE/NEW - LCMS/Preprocessing - xcms.* (3.0.0): upgrade the xcms version from 1.46.0 to 3.0.0. Note that there aren't any retro compatibility between xcms1.46.0 and xcms3.0.0. You have to run the whole workflow from scratch
- NEW in Docker - ALL/Statistics - mixmodel ANOVA for repeated measures statistics
- NEW in Docker - ALL/Statistics - ASCA Splitting of the total variance into independent blocks according to the experimental factors and multivariate analysis (SCA) of each block
- NEW in Docker - LCMS/Annotation - bank_inhouse search by accurate mass (and by Retention time) on a local bank
- NEW in Docker - NMR/Annotation - NMR_Annotation Annotation of complex mixture NMR spectra and metabolite proportion estimation
- UPGRADE
  - LCMS/Preprocessing - camera.*
  - FIAMS/Preprocessing - Profia
  - GCMS/Preprocessing - MetaMS
  - NMR/Preprocessing - NMR preprocessing, NMR alignment, NMR bucketing
  - ALL/Quality Metric - Normalization, Transformation, Quality Metrics, Multilevel
  - ALL/Statistics - Univariate, Multivariate, Anova
  - LCMS/Annotation - HMDB MS search, Lipidmaps

### CODE REVIEW

**Comment by lecorguille** [comment]
ping @pkrog (note that I rename the file which contain the tool)

**Comment by bgruening** [comment]
@lecorguille please let me know if I should get this into https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/master/metabolomics.yaml as well.

**Comment by lecorguille** [comment]
Sure
I can update it if you want ( that way, we are sure that you didn't steal them 😛 )

**Comment by bgruening** [comment]
Urgs, ok please prevent me from doing this :)

**Pull request merged**
